# Generated by Django 2.2.6 on 2019-10-30 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'default_related_name': 'donations'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='users.Customer'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='medical_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='users.MedicalInstitution'),
        ),
    ]
