# Generated by Django 2.2.6 on 2019-10-30 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_datetime', models.DateTimeField()),
                ('is_willing_for_transfusion', models.BooleanField(default=False)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Customer')),
                ('medical_institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.MedicalInstitution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
