# Generated by Django 2.2.6 on 2019-10-30 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('event_datetime', models.DateTimeField()),
                ('contact_number', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('medical_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MedicalInstitution')),
            ],
        ),
    ]
