# Generated by Django 2.2.6 on 2019-10-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='rewards',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
