# Generated by Django 2.2.6 on 2019-10-30 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customer_rewards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='rewards',
            new_name='points',
        ),
    ]
